### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by otuburg**
Can't wait to see where the fault was.

### CODE REVIEW

**Comment by Dharmmey-1** [comment]
Received... will go through it.

**Comment by Dharmmey-1** [comment]
Hello Nathaniel...
The code seems fine. 

I think the problem is from reading of the file. The data is not read successfully.
Focus on the migrations file.
Comment all links that code has to the database_functions file.
Focus on the fetch_and_send_record_data function... Try to print the file and see if it was read successfully...

If you cant, then I guess the Microsoft Excel app was still left open...

Let me know the feedback

**Comment by otuburg** [comment]
> Hello Nathaniel...
> The code seems fine.
> 
> I think the problem is from reading of the file. The data is not read successfully.
> Focus on the migrations file.
> Comment all links that code has to the database_functions file.
> Focus on the fetch_and_send_record_data function... Try to print the file and see if it was read successfully...
> 
> If you cant, then I guess the Microsoft Excel app was still left open...
> 
> Let me know the feedback

Okay I'll do that.

**Comment by otuburg** [comment]
I followed your steps and but nothing changed and i decided to check the excel files we copied from you. I noticed that my Student_rec file was empty. I believe that's where the problem is coming from.

**Comment by Dharmmey-1** [comment]
Yeah... that was exactly my guess that's why I said you should attempt to read the file only.
Have you collected the file again from Ferdinand?

**Comment by otuburg** [comment]
Yes I have, I'll go through it and give you feedback.

**Comment by Dharmmey-1** [comment]
Alright... once there's data in the file, it will work... your code is fine...
Really strange how the data got wiped.

**Comment by otuburg** [comment]
It has worked! Maria got nothing on me now. Thanks!

**Comment by Dharmmey-1** [comment]
Lol... Great!

**Pull request merged**
